-- DESARROLLAR EL CODIGO SQL PARA CREAR LA TABLA DE WORKSPACES 
CREATE TABLE workspaces (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);